# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "@guillaumekuc.blog"
email: "guillaume@guillaumekuc.com"
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://guillaumekuc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
profile: /assets/img/profilePic.jpg
logo: /assets/img/logo.svg
repository: guillaumekuc/blog.git


colors:
  - name: "Teal"
    color: "#20a0af" 
    default: true
  - name: "Coral"
    color: "#F26061"
  - name: "Olive"
    color: "#699E48"
  - name: "Lavender"
    color: "#b080c2"
  - name: "Bronze"
    color: "#a68e53"
     
      

      

socials:
  - title: "Portfolio"
    url: "https://guillaumekuc.art"
    icon: "fa-solid fa-palette"
    alt: "Portfolio"
  - title: "ArtStation"
    icon: "fa-brands fa-artstation"
    url: "https://artstation.com/guillaumekuc"
    alt: "ArtStation"
  - title: "SoundCloud"
    icon: "fa-brands fa-soundcloud"
    url: "https://soundcloud.com/guillaume-kuc-945925946"
    alt: "SoundCloud"
  - title: "Github"
    url: "https://github.com/guillaumekuc"
    icon: "fa-brands fa-github"
    alt: "Github"
  - title: "Bluesky"
    url: "https://bsky.app/profile/guillaumekuc.bsky.social"
    icon: "fa-brands fa-bluesky"
    alt: "Bluesky"
  - title: "Email"
    icon: "fa-solid fa-envelope"
    url: "mailto:guillaume@guillaumekuc.com"
    alt: "guillaume@guillaumekuc.com"

authors:
  guillaumekuc:
    name: "Guillaume Kuc"
    url: "https://guillaumekuc.github.io/links"

credits: 'Â© 2025 <a href="https://guillaumekuc.github.io/links">Guillaume Kuc</a> &mdash; Powered by <a href="https://jekyllrb.com/">Jekyll</a> &mdash; Base theme: <a href="https://github.com/pages-themes/minimal">Minimal</a>'

# Permalink structure (uses title only, no date paths)
permalink: /:title/

# Build settings
#theme: minima
remote_theme: pages-themes/minimal
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-inline-svg

whitelist:
  - jekyll-inline-svg

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
